baseURL = ""
languageCode = "en-us"
tagline = "Data Scientist"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 100
googleAnalytics = ""   # <---- disable analytics

[menu]

  [[menu.main]]
  name = "Home"
  URL = "/"
  weight = 1

  [[menu.main]]
  name = "Tags"
  URL = "/tags"
  weight = 2

  [[menu.main]]
  name = "Categories"
  URL = "/categories"
  weight = 3

  [[menu.main]]
  name = "Projects"
  URL = "/projects"
  weight = 4

  [[menu.main]]
  name = "Recipes"
  URL = "/recipes"
  weight = 5

[author]
email = "tom.andrew.wilson@gmail.com"
name = "Thomas Wilson"
location = "Pennsylvania"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
