baseURL = "https://wilsonify.github.io/"
languageCode = "en-us"
title = "Data Scientist"

DefaultContentLanguage = "en"

[pagination]
  pagerSize = 100

[menu]

  [[menu.main]]
  name = "Home"
  URL = "/"
  weight = 1

  [[menu.main]]
  name = "Tags"
  URL = "/tags"
  weight = 2

  [[menu.main]]
  name = "Categories"
  URL = "/categories"
  weight = 3

  [[menu.main]]
  name = "Projects"
  URL = "/projects"
  weight = 4

  [[menu.main]]
  name = "Recipes"
  URL = "/recipes"
  weight = 5

[author]
  name = "Thomas Wilson"
  email = "tom.andrew.wilson@gmail.com"
  location = "Pennsylvania"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
