version: '3'

services:
  hugo:
    env_file: .env
    container_name: hugo
    image: "ghcr.io/peaceiris/hugo-extended-docker/hugo:latest-full"
    ports:
      - 1313:1313
    volumes:
      - ${PWD}:/src
    command:
      - server
      - --bind=0.0.0.0
      - --buildDrafts