name: github pages

on:
  workflow_dispatch:
  pull_request:
    types:
      - synchronize

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Render site
        run: docker run --rm --name builder -v ${{ github.workspace }}:/usr/src/app ghcr.io/wilsonify/wilsonify.github.io.builder:master hugo --minify

      - name: update gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4